name: DEPLOY TEST
on:
  pull_request:
    types: [labeled, opened, reopened, synchronize]
jobs:
  new_flow:
    runs-on: ubuntu-latest
    steps:
      - run: echo Just open a new file for the PR to test
